name: Second_workflow
on:
  workflow_run:
    workflows:
        - Main_workflow
    types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Running
      run: echo "Running"
  

